### ISSUE TITLE
Implement ability to assign codes to a site

### ISSUE THREAD

**Issue by m-martinez** [razorlabs/occams#23]
The `site` table currently only stores the machine-generated `name` for the site. We should re-purpose this column and allow site coordinators to manually assign a "code" for a site, such as:

>    apla-hucla “31"
>    the-hucla “33"

Unfortunately, the name directly maps to LDAP groups which will cause things to fall out of sync. For the time being we should introduce a `code` column and use this for the URL and reported site codes. This may impact reporting so we should coordinate with data consumers first.
### TODO
- [] Add new `code` column to database and corresponding audit table
- [] Update sqlalchemy models and corresponding API endpoints to expose this field
- [] Add new validated UI field to site modal
- [] Update routing to use site {{code}} instead of {{name}}
- [] Amend unit tests and add new ones
